using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Codegen;

[Generator]
public class EqualsAndHashCodeGenerator : IIncrementalGenerator
{
    private const string AttributeSourceCode = @"
// <auto-generated/>

namespace Codegen;

[System.AttributeUsage(System.AttributeTargets.Class)]
public class EqualsAndHashCodeAttribute: System.Attribute
{
}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "EqualsAndHashCodeAttribute",
            SourceText.From(AttributeSourceCode, Encoding.UTF8)));
    }
}